server:
  port: 8080
spring:
    application:
        name: lbm-inventory
    security:
        oauth2:
            client:
                provider:
                    azure:
                        issuer-uri: https://login.microsoftonline.com/${TENANT_ID}/v2.0
                registration:
                    azure-dev:
                        provider: azure
                        client-id: ${CLIENT_ID}
                        client-secret: ${CLIENT_SECRET}
                        scope: 
                            - openid
                            - profile
                            - email
                        redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
                        authorization-grant-type: authorization_code
            resourceserver:
                jwt:
                    issuer-uri: https://login.microsoftonline.com/${TENANT_ID}/v2.0
                    jwk-set-uri: https://login.microsoftonline.com/${TENANT_ID}/discovery/v2.0/keys
    datasource:
        url: jdbc:postgresql://db:5432/inventory_db
        username: postgres
        password: changeme
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
    sql:
        init:
            mode: never
    profiles:
        active: dev
logging:
    level:
        '[org.springframework.ws]': DEBUG
        '[org.springframework.security]': DEBUG
        '[org.springframework.web]': DEBUG
        
